### ISSUE TITLE
Records with multiple DOIs associated with them

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/idsidsids#3]
My reading of the Plan-S requirements:

> 2.1) MANDATORY: Use of PIDs for the deposited versions of the publications (with versioning, for example in case of revisions), such as DOI (preferable), URN, or Handle.

is that we will be minting DOIs for full-texts held locally (Accepted versions), as well as the EPrint having a reference to the published version's DOI.

Should this plugin support any form of commentary for the IDs?
I'm thinking
```
* [link to doi A] (Publisher's version)
* [link to doi B] (Accepted version)
...
```

There is also a cyclical link issue - if we're the registered endpoint of a DOI - but I'm not sure the right wat to represent that to a human or machine!

**Comment by drn05r** [comment]
Yes, I did wonder about how to capture extra detail.  As you may see in the code there is a way of enabling a maximum of one ID per any type validation but this is disabled by default, as I suspected that there may be cases for storing two DOIs like you describe.  I think like this validation a commentary field should be included but disabled by default, as it may be something some repositories need but might confuse those who only want the basic functionality.

**Comment by drn05r** [comment]
I think this could quite often be used for print and online ISSN and for different versions of the publication.  It would not be an extra field in the eprint table as ids is a multiple field and therefore gets its own tables,
